### ISSUE TITLE
Make Title screen

### ISSUE THREAD

**Issue by AisteKiskyte** [RusticPorcupineGames/GlobalGameJam2018#2]
- Find a background picture for the title page (web or make one, or change one from the web)
- Put it in Images folder
- Load it in StartScreen.js preload method. see examples on how to load an in 
https://phaser.io/tutorials/making-your-first-phaser-game/part2
- Add it to the game loading screen (also above tutorial)
- Put our logo somewhere same way.
- Make it pretty.

**Comment by JacobBusfield** [comment]
Title screen made successfully by the Alderman-Durkin combo squad.
