### ISSUE TITLE
Find and load some furniture

### ISSUE THREAD

**Issue by AisteKiskyte** [RusticPorcupineGames/GlobalGameJam2018#3]
- Find some isometric furniture on the internet or draw some (example web page - ask Jacob, example drawing tools - ask Matt or Dan).
- Furniture needed, that looks like hospital stuff (expand as you want):
hospital beds, wheelchairs, drug cabinet, exam room table / lamp, reception area, a plant, etc.
- Put it in Images/Furniture folder
- Load it all in Preload.js file, preload method. Examples of how to load images:
https://phaser.io/tutorials/making-your-first-phaser-game/part2

Make sure to give easy names between '', like 'bed1', 'chair2', rather than whatever the file name is.

**Comment by JacobBusfield** [comment]
Furniture was successfully installed by the Morris man.
