### ISSUE TITLE
Add background music to the game

### ISSUE THREAD

**Issue by AisteKiskyte** [RusticPorcupineGames/GlobalGameJam2018#4]
- Find some background music that would seem fitting for a title screen and the main game
- Put it in /Music folder in our project
- Load music in Preload.js
- Start music in StartScreen.js for game title screen; Game.js for the game.

Expect that the music might change later, but at least we have a placeholder of loading it, and only will need to change the path if we find something else. But don't put something bad, in case we run out of time and never change it :)

Tutorials on how to load music (probably just need first one - 'Audio Sprite')
https://phaser.io/examples/v2/category/audio

**Comment by JacobBusfield** [comment]
Completed by Deccers.
